/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.admin;

import Controller.DiemController;
import Controller.LopTCController;
import Controller.MonHocController;
import classObj.LopTC;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import xuly.xuly_All;

/**
 *
 * @author TuanVi
 */
public class QLLopTC extends javax.swing.JFrame {

    public static ArrayList<LopTC> list;
    DefaultTableModel model;
    private boolean ktHK, ktNhom, ktsvmax, ktsvmin;

    /**
     * Creates new form LopTC
     */
    public QLLopTC() {
        initComponents();

//        this.setLocationRelativeTo(null);
        list = LopTCController.layDanhSachLopTC();
        model = (DefaultTableModel) jTable1.getModel();

        model.setColumnIdentifiers(new Object[]{
            "Mã lớp", "Mã môn học", "Niên khoá", "Học kỳ", "Nhóm", "SVMax", "SVMin"
        });
        showTable();
        loadComboBoxMaMH();
        taoma();
    }

    public void showTable() {
        for (LopTC loptc : list) {

            model.addRow(new Object[]{
                loptc.getMaLop(), loptc.getMaMH(), loptc.getNienKhoa(), loptc.getHocKy(), loptc.getNhom(),
                loptc.getSvMax(), loptc.getSvMin()
            });
        }
    }

    public void taoma() {
        int malop = xuly_All.taoMaLop();
        jTextField_maLop.setText(String.valueOf(malop));
    }

    public void reSet() {
        jTextField_hocKy.setText("");
        jTextField_nhom.setText("");
        jTextField_svmax.setText("");
        jTextField_svmin.setText("");
        jLabel_loiSVMax.setText("");
        jLabel_loiSVmin.setText("");
        jLabel_loihocKy.setText("");
        jLabel_loinhom.setText("");

    }

    public void resetTable() {
        DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
        dm.setNumRows(0);
    }

    public void loadComboBoxMaMH() {
        for (Object object : MonHocController.getAllmaMonHoc()) {
            jComboBox_maMonHoc.addItem(String.valueOf(object));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_maLop = new javax.swing.JTextField();
        jComboBox_maMonHoc = new javax.swing.JComboBox<>();
        jComboBox_nienKhoa = new javax.swing.JComboBox<>();
        jTextField_hocKy = new javax.swing.JTextField();
        jTextField_nhom = new javax.swing.JTextField();
        jTextField_svmax = new javax.swing.JTextField();
        jTextField_svmin = new javax.swing.JTextField();
        jButton_them = new javax.swing.JButton();
        jButton_xoa = new javax.swing.JButton();
        jButton_sua = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField_timKiem = new javax.swing.JTextField();
        jLabel_malop = new javax.swing.JLabel();
        jLabel_loihocKy = new javax.swing.JLabel();
        jLabel_loinhom = new javax.swing.JLabel();
        jLabel_loiSVMax = new javax.swing.JLabel();
        jLabel_loiSVmin = new javax.swing.JLabel();
        jButton_thoat = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ LỚP TÍN CHỈ");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã lớp", "Mã môn học", "Niên khóa", "Học kỳ", "Nhóm", "SVMax", "SVMin"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(40);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 663, 330));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Mã lớp");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Mã môn học");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 205, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Niên khóa");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Học kỳ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 335, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Nhóm");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 395, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("SVMax");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 455, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("SVMin");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 515, -1, -1));

        jTextField_maLop.setEditable(false);
        getContentPane().add(jTextField_maLop, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 261, -1));

        jComboBox_maMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_maMonHocActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_maMonHoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 261, -1));

        jComboBox_nienKhoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2010-2011", "2011-2012", "2012-2013", "2013-2014", "2014-2015", "2015-2016", "2016-2017", "2017-2018", "2018-2019", "2019-2020", "2020-2021", "2021-2022", "2022-2023" }));
        jComboBox_nienKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_nienKhoaActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_nienKhoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 261, -1));

        jTextField_hocKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_hocKyActionPerformed(evt);
            }
        });
        jTextField_hocKy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_hocKyKeyReleased(evt);
            }
        });
        getContentPane().add(jTextField_hocKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 260, -1));

        jTextField_nhom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nhomActionPerformed(evt);
            }
        });
        jTextField_nhom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_nhomKeyReleased(evt);
            }
        });
        getContentPane().add(jTextField_nhom, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 262, -1));

        jTextField_svmax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_svmaxKeyReleased(evt);
            }
        });
        getContentPane().add(jTextField_svmax, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 261, -1));

        jTextField_svmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_svminActionPerformed(evt);
            }
        });
        jTextField_svmin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_svminKeyReleased(evt);
            }
        });
        getContentPane().add(jTextField_svmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, 261, -1));

        jButton_them.setText("Thêm");
        jButton_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_themActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_them, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 576, 110, -1));

        jButton_xoa.setText("Xóa");
        jButton_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_xoaActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 576, 100, -1));

        jButton_sua.setText("Sửa");
        jButton_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_suaActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 576, 100, -1));

        jLabel10.setText("Tìm kiếm");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 60, -1));

        jTextField_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_timKiemActionPerformed(evt);
            }
        });
        jTextField_timKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_timKiemKeyReleased(evt);
            }
        });
        getContentPane().add(jTextField_timKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 281, -1));

        jLabel_malop.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(jLabel_malop, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 260, 10));

        jLabel_loihocKy.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_loihocKy.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jLabel_loihocKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 261, 10));

        jLabel_loinhom.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jLabel_loinhom, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 420, 260, 10));

        jLabel_loiSVMax.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel_loiSVMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 261, 10));

        jLabel_loiSVmin.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jLabel_loiSVmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 536, 261, 10));

        jButton_thoat.setText("Thoát");
        jButton_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_thoatActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_thoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 576, 100, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 102));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("HỌC VIỆN CÔNG NGHỆ BƯU CHÍNH VIỄN THÔNG ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 35, 497, 39));

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 102));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("CƠ SỞ TP HỒ CHÍ MINH");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 263, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_xoaActionPerformed
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(rootPane, "Chọn Mã lớp cần xoá!!!");
        } else {

            int confirm = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc muốn Xóa không?");
            if (confirm == JOptionPane.YES_OPTION) {
                int maLop = Integer.valueOf(String.valueOf(jTable1.getValueAt(row, 0)));
                if (DiemController.ktLopTC(maLop) == true) {
                    JOptionPane.showMessageDialog(rootPane, "Lớp tín chỉ đang có sinh viên học!!!");
                } else {
                    LopTCController.xoaLopTC(maLop);
                    list.remove(row);
                    resetTable();
                    try {
                        showTable();
                    } catch (Exception ex) {
                        Logger.getLogger(QLLopTC.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton_xoaActionPerformed

    private void jTextField_nhomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nhomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nhomActionPerformed

    private void jTextField_svminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_svminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_svminActionPerformed

    private void jButton_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_themActionPerformed

        if (ktHK == true && ktNhom == true && ktsvmax == true && ktsvmin == true) {
            LopTC loptc = new LopTC();
            loptc.setMaLop(Integer.valueOf(jTextField_maLop.getText()));
            loptc.setMaMH((String) jComboBox_maMonHoc.getSelectedItem());
            loptc.setNienKhoa((String) jComboBox_nienKhoa.getSelectedItem());
            loptc.setHocKy(Integer.parseInt(jTextField_hocKy.getText()));
            loptc.setNhom(Integer.parseInt(jTextField_nhom.getText()));
            loptc.setSvMax(Integer.parseInt(jTextField_svmax.getText()));
            loptc.setSvMin(Integer.parseInt(jTextField_svmin.getText()));
            LopTC ktLoptc = LopTCController.getLopWhere(loptc.getMaMH(), loptc.getNienKhoa(), loptc.getNhom(), loptc.getHocKy());
            if (Integer.valueOf(jTextField_svmin.getText()) > Integer.valueOf(jTextField_svmax.getText())
                    || Integer.valueOf(jTextField_svmin.getText()) == Integer.valueOf(jTextField_svmax.getText())) {
                JOptionPane.showMessageDialog(rootPane, "Sinh viên min không được lớn hơn hoặc bằng Sinh viên max!!!");
            } else if (ktLoptc != null) {
                JOptionPane.showMessageDialog(rootPane, "Không được trùng Mã Môn Học, Niên Khoá, Nhóm, Học Kỳ!!!");
            } else {
                int confirm = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc muốn Thêm không?");
                if (confirm == JOptionPane.YES_OPTION) {
                    try {
                        LopTCController.themLopTC(loptc);
                        JOptionPane.showMessageDialog(rootPane, "Thêm thành công!!!");
                        reSet();
                        list.add(loptc);
                        showResult();
                        taoma();
                        ktHK = false;
                        ktNhom = false;
                        ktsvmax = false;
                        ktsvmin = false;
                    } catch (Exception e) {
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Không được để trống!!!");
        }


    }//GEN-LAST:event_jButton_themActionPerformed

    private void jButton_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_suaActionPerformed
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn người dùng!!!");

        } else {
            int maLop = Integer.valueOf(String.valueOf(jTable1.getValueAt(row, 0)));
            new SuaLopTC(maLop).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton_suaActionPerformed

    private void jTextField_timKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_timKiemKeyReleased
        DefaultTableModel table = (DefaultTableModel) jTable1.getModel();
        String search = jTextField_timKiem.getText().toLowerCase();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        jTable1.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search, 0));
    }//GEN-LAST:event_jTextField_timKiemKeyReleased

    private void jTextField_hocKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_hocKyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_hocKyActionPerformed

    private void jComboBox_nienKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_nienKhoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_nienKhoaActionPerformed

    private void jTextField_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_timKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_timKiemActionPerformed

    private void jComboBox_maMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_maMonHocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_maMonHocActionPerformed

    private void jTextField_hocKyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_hocKyKeyReleased
        String regexHK = "^[123]$";
        String megHK = "Học kì không được để trống!!!";
        String reHK = "Định dạng học kì không đúng!!!";
        if (jTextField_hocKy.getText().equals("")) {
            jLabel_loihocKy.setText(megHK);
            jLabel_loihocKy.setVisible(true);
            ktHK = false;
        } else if (!jTextField_hocKy.getText().matches(regexHK)) {
            jLabel_loihocKy.setText(reHK);
            jLabel_loihocKy.setVisible(true);
            ktHK = false;
        } else {
            jLabel_loihocKy.setVisible(false);
            ktHK = true;
        }
    }//GEN-LAST:event_jTextField_hocKyKeyReleased

    private void jTextField_nhomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nhomKeyReleased
        String regexNhom = "^\\d$";
        String megNhom = "Nhóm không được để trống!!!";
        String reNhom = "Định dạng nhóm không đúng!!!";
        if (jTextField_nhom.getText().equals("")) {
            jLabel_loinhom.setText(megNhom);
            jLabel_loinhom.setVisible(true);
            ktNhom = false;
        } else if (!jTextField_nhom.getText().matches(regexNhom)) {
            jLabel_loinhom.setText(reNhom);
            jLabel_loinhom.setVisible(true);
            ktNhom = false;
        } else {
            ktNhom = true;
            jLabel_loinhom.setVisible(false);
        }
    }//GEN-LAST:event_jTextField_nhomKeyReleased

    private void jTextField_svmaxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_svmaxKeyReleased
        String regexSvMax = "^[12][0-9][0-9]?$|^[3-9][0-9]$";
        String megSVMax = "Điền vào số sinh viên max!!!";
        String regexmax = "max > 10 && max < 300";
        if (jTextField_svmax.getText().equals("")) {
            jLabel_loiSVMax.setText(megSVMax);
            jLabel_loiSVMax.setVisible(true);
            ktsvmax = false;
        } else if (!jTextField_svmax.getText().matches(regexSvMax)) {
            jLabel_loiSVMax.setText(regexmax);
            jLabel_loiSVMax.setVisible(true);
            ktsvmax = false;
        } else {
            ktsvmax = true;
            jLabel_loiSVMax.setVisible(false);
        }
    }//GEN-LAST:event_jTextField_svmaxKeyReleased

    private void jTextField_svminKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_svminKeyReleased
        String regexSvMin = "^[1-9][0-9]$";
        String regexMin = "min > 10 && min < 100";
        String megSVMin = "Điền vào số sinh viên min!!!";
        if (jTextField_svmin.getText().equals("")) {
            jLabel_loiSVmin.setText(megSVMin);
            jLabel_loiSVmin.setVisible(true);
            ktsvmin = false;
        } else if (!jTextField_svmin.getText().matches(regexSvMin)) {
            jLabel_loiSVmin.setText(regexMin);
            jLabel_loiSVmin.setVisible(true);
            ktsvmin = false;
        } else {
            ktsvmin = true;
            jLabel_loiSVmin.setVisible(false);
        }
    }//GEN-LAST:event_jTextField_svminKeyReleased

    private void jButton_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_thoatActionPerformed
        this.dispose();
        new Views.admin.QuanTriVien().setVisible(true);
    }//GEN-LAST:event_jButton_thoatActionPerformed

    public void showResult() {
        LopTC loptc = list.get(list.size() - 1);
        model.addRow(new Object[]{
            loptc.getMaLop(), loptc.getMaMH(), loptc.getNienKhoa(), loptc.getHocKy(), loptc.getNhom(),
            loptc.getSvMax(), loptc.getSvMin()
        });
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(QLLopTC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(QLLopTC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(QLLopTC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(QLLopTC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new QLLopTC().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_sua;
    private javax.swing.JButton jButton_them;
    private javax.swing.JButton jButton_thoat;
    private javax.swing.JButton jButton_xoa;
    private javax.swing.JComboBox<String> jComboBox_maMonHoc;
    private javax.swing.JComboBox<String> jComboBox_nienKhoa;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_loiSVMax;
    private javax.swing.JLabel jLabel_loiSVmin;
    private javax.swing.JLabel jLabel_loihocKy;
    private javax.swing.JLabel jLabel_loinhom;
    private javax.swing.JLabel jLabel_malop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_hocKy;
    private javax.swing.JTextField jTextField_maLop;
    private javax.swing.JTextField jTextField_nhom;
    private javax.swing.JTextField jTextField_svmax;
    private javax.swing.JTextField jTextField_svmin;
    private javax.swing.JTextField jTextField_timKiem;
    // End of variables declaration//GEN-END:variables
}
