/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.admin;

import Controller.DiemController;
import Controller.LopController;
import Controller.SinhVienController;
import classObj.Sinhvien;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import xuly.xuly_All;

/**
 *
 * @author Admin
 */
public class QuanLy_SV extends javax.swing.JFrame {

    private boolean ktMssv, ktHoten, ktDiachi, ktNamNh, ktdate, ktSDT;

    /**
     * Creates new form QuanLy_SV
     */
    public QuanLy_SV() throws Exception {
        initComponents();
        layDanhSachSinhVien();
        LoadComboboxMaLop();
    }

    private void layDanhSachSinhVien() throws Exception {
        DefaultTableModel dtm = (DefaultTableModel) dsTable_SV.getModel();
        dtm.setNumRows(0);
        Vector ds = SinhVienController.getdsSinhVien();
        for (Object d : ds) {
            dtm.addRow((Vector) d);
        }
        dsTable_SV.setModel(dtm);

    }

    private void LoadComboboxMaLop() {
        ArrayList getAll = LopController.getAllmaLop();
        for (Object object : getAll) {
            jComboBox_MALOP.addItem((String) object);
        }
    }

    private void setAlljTextField() {
        jTextField_DIACHI.setText("");
        jTextField_HOTEN.setText("");
        jTextField_NGAYSINH.setText("");
        jTextField_SDT.setText("");
        jTextField_NAMNH.setText("");
        jTextField_MASV.setText("");
        jComboBox_MALOP.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jTextField_MASV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_NGAYSINH = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_HOTEN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton_NAM = new javax.swing.JRadioButton();
        jRadioButton_NU = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField_NAMNH = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_DIACHI = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBox_MALOP = new javax.swing.JComboBox<>();
        jButton_THEM = new javax.swing.JButton();
        jButton_XOA = new javax.swing.JButton();
        jButton_SUA = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        dsTable_SV = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jTextField_SDT = new javax.swing.JTextField();
        jTextField_Search = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel_loiMssv = new javax.swing.JLabel();
        jLabel_loingaysinh = new javax.swing.JLabel();
        jLabel_loiNamnh = new javax.swing.JLabel();
        jLabel_Hoten = new javax.swing.JLabel();
        jLabel_loiDST = new javax.swing.JLabel();
        jLabel_loiDiachi = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ SINH VIÊN");
        setBackground(new java.awt.Color(153, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Mã số sinh viên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 52, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        jTextField_MASV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_MASVActionPerformed(evt);
            }
        });
        jTextField_MASV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_MASVKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_MASVKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_MASVKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 203;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(48, 23, 0, 0);
        getContentPane().add(jTextField_MASV, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Ngày Sinh");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 28, 0, 0);
        getContentPane().add(jLabel3, gridBagConstraints);

        jTextField_NGAYSINH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_NGAYSINHKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 58;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 203;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(48, 18, 0, 0);
        getContentPane().add(jTextField_NGAYSINH, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Họ Tên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 52, 0, 0);
        getContentPane().add(jLabel4, gridBagConstraints);

        jTextField_HOTEN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_HOTENKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 203;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 23, 0, 0);
        getContentPane().add(jTextField_HOTEN, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Giới Tính");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 28, 0, 0);
        getContentPane().add(jLabel5, gridBagConstraints);

        buttonGroup1.add(jRadioButton_NAM);
        jRadioButton_NAM.setText("Nam");
        jRadioButton_NAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_NAMActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 18, 0, 0);
        getContentPane().add(jRadioButton_NAM, gridBagConstraints);

        buttonGroup1.add(jRadioButton_NU);
        jRadioButton_NU.setText("Nữ");
        jRadioButton_NU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_NUActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 21;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 36;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 34, 0, 0);
        getContentPane().add(jRadioButton_NU, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Năm Nhập Học");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 28, 0, 0);
        getContentPane().add(jLabel6, gridBagConstraints);

        jTextField_NAMNH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_NAMNHKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 58;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 203;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        getContentPane().add(jTextField_NAMNH, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Địa Chỉ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 52, 0, 0);
        getContentPane().add(jLabel7, gridBagConstraints);

        jTextField_DIACHI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_DIACHIKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 205;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(39, 23, 0, 0);
        getContentPane().add(jTextField_DIACHI, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Mã Lớp");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 28, 0, 0);
        getContentPane().add(jLabel8, gridBagConstraints);

        jComboBox_MALOP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox_MALOP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Chọn Lớp--" }));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jComboBox_MALOP, org.jdesktop.beansbinding.ELProperty.create("chon lớp"), jComboBox_MALOP, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        jComboBox_MALOP.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_MALOPItemStateChanged(evt);
            }
        });
        jComboBox_MALOP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBox_MALOPFocusGained(evt);
            }
        });
        jComboBox_MALOP.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jComboBox_MALOPInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jComboBox_MALOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_MALOPActionPerformed(evt);
            }
        });
        jComboBox_MALOP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox_MALOPKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jComboBox_MALOPKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jComboBox_MALOPKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 21;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 18, 0, 0);
        getContentPane().add(jComboBox_MALOP, gridBagConstraints);

        jButton_THEM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_THEM.setText("THÊM");
        jButton_THEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_THEMActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 23, 0, 0);
        getContentPane().add(jButton_THEM, gridBagConstraints);

        jButton_XOA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_XOA.setText("XOÁ");
        jButton_XOA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XOAActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 40, 0, 0);
        getContentPane().add(jButton_XOA, gridBagConstraints);

        jButton_SUA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_SUA.setText("SỬA");
        jButton_SUA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SUAActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 0, 0);
        getContentPane().add(jButton_SUA, gridBagConstraints);

        dsTable_SV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Sinh Viên", "Mã lớp", "Họ tên", "Ngày sinh", "Giới Tính", "Số điện thoại", "Năm nhập học", "Địa Chỉ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        dsTable_SV.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                dsTable_SVAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        dsTable_SV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dsTable_SVMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(dsTable_SV);
        if (dsTable_SV.getColumnModel().getColumnCount() > 0) {
            dsTable_SV.getColumnModel().getColumn(0).setMinWidth(50);
            dsTable_SV.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.gridwidth = 75;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 846;
        gridBagConstraints.ipady = 87;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(28, 52, 0, 115);
        getContentPane().add(jScrollPane2, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Số điện thoại");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 52, 0, 0);
        getContentPane().add(jLabel9, gridBagConstraints);

        jTextField_SDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_SDTKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 203;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 23, 0, 0);
        getContentPane().add(jTextField_SDT, gridBagConstraints);

        jTextField_Search.setToolTipText("");
        jTextField_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_SearchActionPerformed(evt);
            }
        });
        jTextField_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_SearchKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 16;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 293;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 40, 0, 0);
        getContentPane().add(jTextField_Search, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Tìm kiếm sinh viên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 35, 0, 0);
        getContentPane().add(jLabel10, gridBagConstraints);

        jLabel_loiMssv.setForeground(new java.awt.Color(255, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 209;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 23, 0, 0);
        getContentPane().add(jLabel_loiMssv, gridBagConstraints);

        jLabel_loingaysinh.setForeground(new java.awt.Color(255, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 58;
        gridBagConstraints.ipadx = 209;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 18, 0, 0);
        getContentPane().add(jLabel_loingaysinh, gridBagConstraints);

        jLabel_loiNamnh.setForeground(new java.awt.Color(255, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 58;
        gridBagConstraints.ipadx = 209;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 18, 0, 0);
        getContentPane().add(jLabel_loiNamnh, gridBagConstraints);

        jLabel_Hoten.setForeground(new java.awt.Color(255, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 209;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 23, 0, 0);
        getContentPane().add(jLabel_Hoten, gridBagConstraints);

        jLabel_loiDST.setForeground(new java.awt.Color(255, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 209;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 23, 0, 0);
        getContentPane().add(jLabel_loiDST, gridBagConstraints);

        jLabel_loiDiachi.setForeground(new java.awt.Color(255, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 211;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 23, 0, 0);
        getContentPane().add(jLabel_loiDiachi, gridBagConstraints);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("THOÁT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 36;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 37;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 11, 0, 0);
        getContentPane().add(jButton1, gridBagConstraints);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton_NAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_NAMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_NAMActionPerformed

    private void jTextField_MASVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_MASVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_MASVActionPerformed

    private void jComboBox_MALOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_MALOPActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_MALOPActionPerformed

    private void jButton_THEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_THEMActionPerformed
        // TODO add your handling code here:
        String Gioitinh = null;
        String MASV = jTextField_MASV.getText().toUpperCase().trim();
        String HoTen = jTextField_HOTEN.getText().trim();
        String NgaySinh = jTextField_NGAYSINH.getText().trim();
        String SDT = jTextField_SDT.getText().trim();
        String DiaChi = jTextField_DIACHI.getText().trim();
        String NAMNH = jTextField_NAMNH.getText().trim();
        if (ktDiachi == true && ktHoten == true && ktMssv == true && ktNamNh == true && ktSDT == true && ktdate == true) {
            if (jComboBox_MALOP.getSelectedItem().equals("--Chọn Lớp--")) {
                JOptionPane.showMessageDialog(this, "Bạn chưa chọn lớp!!!");
            } else if (!jRadioButton_NAM.isSelected() && !jRadioButton_NU.isSelected()) {
                JOptionPane.showMessageDialog(this, "Bạn chưa chọn giới tính!!!");
            } else if (SinhVienController.ktTrung_MASV(MASV) != null) {
                JOptionPane.showMessageDialog(this, "Mã sinh viên không được trùng!!!");
            } else {
                HoTen = xuly_All.chuanHoaDanhTuRieng(HoTen);
                DiaChi = xuly_All.chuanHoaDanhTuRieng(DiaChi);
                if (jRadioButton_NAM.isSelected()) {
                    Gioitinh = jRadioButton_NAM.getText();
                } else {
                    Gioitinh = jRadioButton_NU.getText();
                }
                int confirm = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc muốn Thêm không?");
                if (confirm == JOptionPane.YES_OPTION) {
                    try {
                        Sinhvien sv = new Sinhvien(MASV, HoTen, NgaySinh, DiaChi, Integer.valueOf(NAMNH), (String) jComboBox_MALOP.getSelectedItem(), SDT, Gioitinh, "123456");
                        SinhVienController.themSinhVien(sv);
                        setAlljTextField();
                        layDanhSachSinhVien();
                        ktMssv = false;
                        ktHoten = false;
                        ktDiachi = false;
                        ktNamNh = false;
                        ktdate = false;
                        ktSDT = false;
                        JOptionPane.showMessageDialog(this, "Thêm thành công!!!");
                    } catch (Exception ex) {
                        Logger.getLogger(QuanLy_SV.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Không được bỏ trống!!!");
        }
    }//GEN-LAST:event_jButton_THEMActionPerformed

    private void jRadioButton_NUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_NUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_NUActionPerformed

    private void jButton_XOAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XOAActionPerformed
        // TODO add your handling code here:
        int row = dsTable_SV.getSelectedRow();
        if (row != -1) {
            int confirm = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc muốn Xoá không?");
            if (confirm == JOptionPane.YES_OPTION) {
                String masv = String.valueOf(dsTable_SV.getValueAt(row, 1));
                if (SinhVienController.ktTrung_MASV(masv) == null) {
                    JOptionPane.showMessageDialog(this, "Mã sinh vien không tồn tại!!!");
                }else if(DiemController.ktSinhVien(masv)==true){
                     JOptionPane.showMessageDialog(this, "Sinh vien tồn tại trong loptc không thể xoá!!!");
                } 
                else {
                    try {
                        SinhVienController.xoaSinhVien(masv);
                        layDanhSachSinhVien();
                        JOptionPane.showMessageDialog(this, "Xoá thành công!!!");
                    } catch (Exception ex) {
                        Logger.getLogger(QuanLy_SV.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            }

        } else {
            JOptionPane.showMessageDialog(this, "Chọn Mã Sinh viên cần Xoá!!! ");
        }
    }//GEN-LAST:event_jButton_XOAActionPerformed

    private void jTextField_MASVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_MASVKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_MASVKeyPressed

    private void jTextField_MASVKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_MASVKeyReleased
        if (jTextField_MASV.getText().equals("")) {
            jLabel_loiMssv.setText("Mã sinh viên không được bỏ trống!!!");
            jLabel_loiMssv.setVisible(true);
            ktMssv = false;
        } else {
            jLabel_loiMssv.setVisible(false);
            ktMssv = true;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_MASVKeyReleased

    private void jTextField_MASVKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_MASVKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_MASVKeyTyped

    private void dsTable_SVAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_dsTable_SVAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_dsTable_SVAncestorAdded

    private void jComboBox_MALOPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox_MALOPKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_MALOPKeyReleased

    private void jComboBox_MALOPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox_MALOPKeyTyped

    }//GEN-LAST:event_jComboBox_MALOPKeyTyped

    private void jComboBox_MALOPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox_MALOPKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_MALOPKeyPressed

    private void jComboBox_MALOPItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_MALOPItemStateChanged

    }//GEN-LAST:event_jComboBox_MALOPItemStateChanged

    private void jComboBox_MALOPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox_MALOPFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_MALOPFocusGained

    private void jComboBox_MALOPInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jComboBox_MALOPInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_MALOPInputMethodTextChanged

    private void dsTable_SVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsTable_SVMouseClicked

    }//GEN-LAST:event_dsTable_SVMouseClicked

    private void jTextField_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_SearchActionPerformed

    private void jTextField_SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_SearchKeyReleased
        try {
            Vector getAll = SinhVienController.getALLSVbyMSSVvsHoTen(jTextField_Search.getText());
            DefaultTableModel dtm = (DefaultTableModel) dsTable_SV.getModel();
            dtm.setRowCount(0);
            for (Object object : getAll) {
                dtm.addRow((Vector) object);
            }
            dsTable_SV.setModel(dtm);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jTextField_SearchKeyReleased

    private void jButton_SUAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SUAActionPerformed
        if ((dsTable_SV.getSelectedRow()) == -1) {
            JOptionPane.showMessageDialog(this, "Hãy chọn Sinh Viên!!!");

        } else {
            String malop = (String) dsTable_SV.getValueAt(dsTable_SV.getSelectedRow(), 1);
            new sua_SV(malop, this).setVisible(true);
        }

    }//GEN-LAST:event_jButton_SUAActionPerformed

    private void jTextField_HOTENKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_HOTENKeyReleased
        if (jTextField_HOTEN.getText().equals("")) {
            jLabel_Hoten.setText("Họ tên không được bỏ trống!!!");
            jLabel_Hoten.setVisible(true);
            ktHoten = false;
        } else {
            jLabel_Hoten.setVisible(false);
            ktHoten = true;
        }
    }//GEN-LAST:event_jTextField_HOTENKeyReleased

    private void jTextField_NGAYSINHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_NGAYSINHKeyReleased
        if (jTextField_NGAYSINH.getText().equals("")) {
            jLabel_loingaysinh.setText("Ngày sinh không được bỏ trống!!!");
            jLabel_loingaysinh.setVisible(true);
            ktdate = false;
        } else if (!jTextField_NGAYSINH.getText().trim().matches("\\d{1,2}[-|/]\\d{1,2}[-|/]\\d{4}")) {
            jLabel_loingaysinh.setText("Ngày sinh sai định dạng!!!");
            jLabel_loingaysinh.setVisible(true);
            ktdate = false;
        } else {
            jLabel_loingaysinh.setVisible(false);
            ktdate = true;
        }
    }//GEN-LAST:event_jTextField_NGAYSINHKeyReleased

    private void jTextField_NAMNHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_NAMNHKeyReleased
        if (jTextField_NAMNH.getText().equals("")) {
            jLabel_loiNamnh.setText("Năm nhập học không được bỏ trống!!!");
            jLabel_loiNamnh.setVisible(true);
            ktNamNh = false;
        } else if (!jTextField_NAMNH.getText().trim().matches("\\d{4}")) {
            jLabel_loiNamnh.setText("Năm nhập học không hợp lệ!!!");
            jLabel_loiNamnh.setVisible(true);
            ktNamNh = false;
        } else {
            jLabel_loiNamnh.setVisible(false);
            ktNamNh = true;
        }
    }//GEN-LAST:event_jTextField_NAMNHKeyReleased

    private void jTextField_SDTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_SDTKeyReleased
        if (jTextField_SDT.getText().equals("")) {
            jLabel_loiDST.setText("Số điện thoại không được bỏ trống!!!");
            jLabel_loiDST.setVisible(true);
            ktSDT = false;
        } else if (!jTextField_SDT.getText().trim().matches("0\\d{9,10}")) {
            jLabel_loiDST.setText("Số điện thoại không đúng định dạng!!!");
            jLabel_loiDST.setVisible(true);
            ktSDT = false;
        } else {
            jLabel_loiDST.setVisible(false);
            ktSDT = true;
        }
    }//GEN-LAST:event_jTextField_SDTKeyReleased

    private void jTextField_DIACHIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_DIACHIKeyReleased
        if (jTextField_DIACHI.getText().equals("")) {
            jLabel_loiDiachi.setText("Địa chỉ không được bỏ trống!!!");
            jLabel_loiDiachi.setVisible(true);
            ktDiachi = false;
        } else {
            jLabel_loiDiachi.setVisible(false);
            ktDiachi = true;
        }
    }//GEN-LAST:event_jTextField_DIACHIKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new QuanTriVien().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLy_SV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLy_SV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLy_SV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLy_SV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new QuanLy_SV().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(QuanLy_SV.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTable dsTable_SV;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_SUA;
    private javax.swing.JButton jButton_THEM;
    private javax.swing.JButton jButton_XOA;
    private javax.swing.JComboBox<String> jComboBox_MALOP;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Hoten;
    private javax.swing.JLabel jLabel_loiDST;
    private javax.swing.JLabel jLabel_loiDiachi;
    private javax.swing.JLabel jLabel_loiMssv;
    private javax.swing.JLabel jLabel_loiNamnh;
    private javax.swing.JLabel jLabel_loingaysinh;
    private javax.swing.JRadioButton jRadioButton_NAM;
    private javax.swing.JRadioButton jRadioButton_NU;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_DIACHI;
    private javax.swing.JTextField jTextField_HOTEN;
    private javax.swing.JTextField jTextField_MASV;
    private javax.swing.JTextField jTextField_NAMNH;
    private javax.swing.JTextField jTextField_NGAYSINH;
    private javax.swing.JTextField jTextField_SDT;
    private javax.swing.JTextField jTextField_Search;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
