/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.admin;

import Controller.MonHocController;
import classObj.Monhoc;
import javax.swing.JOptionPane;
import xuly.xuly_All;

/**
 *
 * @author Admin
 */
public class Sua_MonHoc extends javax.swing.JFrame {

    private boolean kttenMH = true, ktSTC = true;
    private Quanly_MonHoc ql;

    public Sua_MonHoc(String maMH, Quanly_MonHoc ql) {
        this.ql = ql;
        initComponents();
        layMonHoc(maMH);
    }

    Sua_MonHoc(String maMH) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel_MAMH = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_tenMH = new javax.swing.JTextField();
        jLabel_loitenMH = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_STC = new javax.swing.JTextField();
        jLabel_loiSTC = new javax.swing.JLabel();
        jButton_sua = new javax.swing.JButton();
        jButton_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SỬA MÔN HỌC");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Mã Môn Học");

        jLabel_MAMH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_MAMH.setForeground(new java.awt.Color(255, 51, 204));
        jLabel_MAMH.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Tên Môn Học");

        jTextField_tenMH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_tenMHKeyReleased(evt);
            }
        });

        jLabel_loitenMH.setForeground(new java.awt.Color(255, 51, 0));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Số tín chỉ");

        jTextField_STC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_STCKeyReleased(evt);
            }
        });

        jLabel_loiSTC.setForeground(new java.awt.Color(255, 51, 0));

        jButton_sua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_sua.setText("Sửa");
        jButton_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_suaActionPerformed(evt);
            }
        });

        jButton_cancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_cancel.setText("Thoát");
        jButton_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(jLabel_loitenMH, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jLabel_MAMH, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_STC, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_tenMH, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_loiSTC, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_cancel)
                        .addGap(110, 110, 110))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_MAMH))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_tenMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_loitenMH, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jTextField_STC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel_loiSTC, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_sua)
                    .addComponent(jButton_cancel))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void layMonHoc(String maMH) {
        Monhoc mh = MonHocController.ktMonhoc(maMH);
        jTextField_STC.setText(String.valueOf(mh.getSTC()));
        jTextField_tenMH.setText(mh.getTenMH());
        jLabel_MAMH.setText(mh.getMAMH());
    }
    private void jTextField_tenMHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_tenMHKeyReleased
        if (jTextField_tenMH.getText().trim().equals("")) {
            jLabel_loitenMH.setText("Tên môn học không được bỏ trống!!!");
            jLabel_loitenMH.setVisible(true);
            kttenMH = false;
        } else {
            kttenMH = true;
            jLabel_loitenMH.setVisible(false);
        };
    }//GEN-LAST:event_jTextField_tenMHKeyReleased

    private void jTextField_STCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_STCKeyReleased
        if (jTextField_STC.getText().trim().equals("")) {
            jLabel_loiSTC.setText("Số tín chỉ không được bỏ trống!!!");
            jLabel_loiSTC.setVisible(true);
            ktSTC = false;
        } else if (!jTextField_STC.getText().trim().matches("\\d")) {
            jLabel_loiSTC.setText("Số tín chỉ sai định dạng!!!");
            jLabel_loiSTC.setVisible(true);
            ktSTC = false;
        } else {
            ktSTC = true;
            jLabel_loiSTC.setVisible(false);
        };
    }//GEN-LAST:event_jTextField_STCKeyReleased

    private void jButton_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_suaActionPerformed
        if (ktSTC = true && kttenMH == true) {
            int confirm = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc muốn Sửa không?");
            if (confirm == JOptionPane.YES_OPTION) {
                String mamh=jLabel_MAMH.getText().trim();
                String tenMH=xuly_All.firstToUpperCase(jTextField_tenMH.getText());
                int stc=Integer.valueOf(jTextField_STC.getText());
                Monhoc mh = new Monhoc(mamh,tenMH,stc);
                MonHocController.update(mh);
                JOptionPane.showMessageDialog(this, "Sửa thành công!!!");
                this.dispose();
                ql.dispose();
                new Quanly_MonHoc().setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Không được bỏ trống!!!");
        }
    }//GEN-LAST:event_jButton_suaActionPerformed

    private void jButton_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sua_MonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sua_MonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sua_MonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sua_MonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cancel;
    private javax.swing.JButton jButton_sua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_MAMH;
    private javax.swing.JLabel jLabel_loiSTC;
    private javax.swing.JLabel jLabel_loitenMH;
    private javax.swing.JTextField jTextField_STC;
    private javax.swing.JTextField jTextField_tenMH;
    // End of variables declaration//GEN-END:variables
}
