/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.admin;

import Views.admin.QuanLy_SV;
import Controller.LopController;
import Controller.SinhVienController;
import classObj.Sinhvien;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import xuly.xuly_All;

/**
 *
 * @author Admin
 */
public class sua_SV extends javax.swing.JFrame {

    private QuanLy_SV a;
    private boolean  ktHoten=true, ktDiachi=true, ktNamNh=true, ktdate=true, ktSDT=true;

    /**
     */
    public sua_SV(String maSV, QuanLy_SV a) {
        this.a = a;
        initComponents();
        LoadComboboxMaLop();
        laySinhVien(maSV);
    }

    private sua_SV() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void LoadComboboxMaLop() {
        ArrayList getAll = LopController.getAllmaLop();
        for (Object object : getAll) {
            jComboBox_malop.addItem((String) object);
        }
    }

    private void laySinhVien(String maSV) {
        jLabel_masv.setText(maSV);
        Sinhvien sv = SinhVienController.ktTrung_MASV(maSV);
        jTextField_diachi.setText(sv.getDiaChi());
        jTextField_sdt.setText(sv.getSDT());
        jTextField_ngaysinh.setText(sv.getNgaySinh());
        jTextField_hoten.setText(sv.getHoTen());
        jTextField_namnh.setText(String.valueOf(sv.getNamNH()));
        jComboBox_malop.setSelectedItem(sv.getMalOP());
        if (sv.getGoiTinh().equals("Nam")) {
            jRadioButton_nam.doClick();
        } else {
            jRadioButton_nu.doClick();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextField_ngaysinh = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_hoten = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton_nam = new javax.swing.JRadioButton();
        jRadioButton_nu = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField_sdt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBox_malop = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jTextField_diachi = new javax.swing.JTextField();
        jButton_sua = new javax.swing.JButton();
        jButton_cancel = new javax.swing.JButton();
        jLabel_masv = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField_namnh = new javax.swing.JTextField();
        jLabel_loingaysinh = new javax.swing.JLabel();
        jLabel_loiHoten = new javax.swing.JLabel();
        jLabel_loinamnh = new javax.swing.JLabel();
        jLabel_loiSdt = new javax.swing.JLabel();
        jLabel_loiDiachi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SỬA SINH VIÊN");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("MÃ SINH VIÊN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(107, 106, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jTextField_ngaysinh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_ngaysinhKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 148;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 18, 0, 0);
        getContentPane().add(jTextField_ngaysinh, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Ngày Sinh");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 73, 0, 0);
        getContentPane().add(jLabel3, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Họ tên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(53, 73, 0, 0);
        getContentPane().add(jLabel5, gridBagConstraints);

        jTextField_hoten.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_hotenKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 148;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(51, 18, 0, 0);
        getContentPane().add(jTextField_hoten, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Giới Tính");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 41, 0, 0);
        getContentPane().add(jLabel6, gridBagConstraints);

        buttonGroup1.add(jRadioButton_nam);
        jRadioButton_nam.setText("Nam");
        jRadioButton_nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_namActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        getContentPane().add(jRadioButton_nam, gridBagConstraints);

        buttonGroup1.add(jRadioButton_nu);
        jRadioButton_nu.setText("Nữ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 23, 0, 0);
        getContentPane().add(jRadioButton_nu, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Số điện thoại");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 41, 0, 0);
        getContentPane().add(jLabel7, gridBagConstraints);

        jTextField_sdt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_sdtKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 17;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 98;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 23, 0, 0);
        getContentPane().add(jTextField_sdt, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Mã lớp");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(53, 41, 0, 0);
        getContentPane().add(jLabel8, gridBagConstraints);

        jComboBox_malop.setToolTipText("");
        jComboBox_malop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_malopActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(51, 19, 0, 0);
        getContentPane().add(jComboBox_malop, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Địa Chỉ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 73, 0, 0);
        getContentPane().add(jLabel9, gridBagConstraints);

        jTextField_diachi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_diachiKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 147;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        getContentPane().add(jTextField_diachi, gridBagConstraints);

        jButton_sua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_sua.setText("SỬA");
        jButton_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_suaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.ipadx = 44;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 18, 60, 0);
        getContentPane().add(jButton_sua, gridBagConstraints);

        jButton_cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_cancel.setText("THOÁT");
        jButton_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 23, 60, 0);
        getContentPane().add(jButton_cancel, gridBagConstraints);

        jLabel_masv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_masv.setText("jLabel10");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 43;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(105, 51, 0, 0);
        getContentPane().add(jLabel_masv, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Năm nhập học");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 73, 0, 0);
        getContentPane().add(jLabel10, gridBagConstraints);

        jTextField_namnh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_namnhKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 148;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 18, 0, 0);
        getContentPane().add(jTextField_namnh, gridBagConstraints);

        jLabel_loingaysinh.setForeground(new java.awt.Color(255, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 154;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 18, 0, 0);
        getContentPane().add(jLabel_loingaysinh, gridBagConstraints);

        jLabel_loiHoten.setForeground(new java.awt.Color(255, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 154;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 0, 0);
        getContentPane().add(jLabel_loiHoten, gridBagConstraints);

        jLabel_loinamnh.setForeground(new java.awt.Color(255, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 153;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 18, 0, 0);
        getContentPane().add(jLabel_loinamnh, gridBagConstraints);

        jLabel_loiSdt.setForeground(new java.awt.Color(255, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 18;
        gridBagConstraints.ipadx = 154;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 23, 0, 131);
        getContentPane().add(jLabel_loiSdt, gridBagConstraints);

        jLabel_loiDiachi.setForeground(new java.awt.Color(255, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 153;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 0, 0);
        getContentPane().add(jLabel_loiDiachi, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton_namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_namActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_namActionPerformed

    private void jButton_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton_cancelActionPerformed

    private void jButton_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_suaActionPerformed
        String Gioitinh = null;
        String HoTen = jTextField_hoten.getText().trim();
        String NgaySinh = jTextField_ngaysinh.getText().trim();
        String SDT = jTextField_sdt.getText().trim();
        String DiaChi = jTextField_diachi.getText().trim();
        String NAMNH = jTextField_namnh.getText().trim();
        if (ktDiachi == true && ktHoten == true  && ktNamNh == true && ktSDT == true && ktdate == true) {
            if (!jRadioButton_nam.isSelected() && !jRadioButton_nu.isSelected()) {
                JOptionPane.showMessageDialog(this, "Bạn chưa chọn giới tính!!!");
            } else {
                HoTen = xuly_All.chuanHoaDanhTuRieng(HoTen);
                DiaChi = xuly_All.chuanHoaDanhTuRieng(DiaChi);
                if (jRadioButton_nam.isSelected()) {
                    Gioitinh = jRadioButton_nam.getText();
                } else {
                    Gioitinh = jRadioButton_nu.getText();
                }
                int confirm = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc muốn Sửa không?");
                if (confirm == JOptionPane.YES_OPTION) {
                    try {
                        SinhVienController.suaSinhVien(jLabel_masv.getText(), HoTen, NgaySinh, DiaChi, Integer.valueOf(NAMNH), (String) jComboBox_malop.getSelectedItem(), SDT, Gioitinh);
                        JOptionPane.showMessageDialog(this, "Sửa thành công!!!");
                        this.setVisible(false);
                        this.a.setVisible(false);
                        new QuanLy_SV().setVisible(true);
                    } catch (Exception ex) {
                        Logger.getLogger(QuanLy_SV.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Không được bỏ trống!!!");
        }
    }//GEN-LAST:event_jButton_suaActionPerformed

    private void jTextField_ngaysinhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ngaysinhKeyReleased

        if (jTextField_ngaysinh.getText().equals("")) {
            jLabel_loingaysinh.setText("Ngày sinh không được bỏ trống!!!");
            jLabel_loingaysinh.setVisible(true);
            ktdate = false;
        } else if (!jTextField_ngaysinh.getText().matches("\\d{1,2}[-|/]\\d{1,2}[-|/]\\d{4}")) {
            jLabel_loingaysinh.setText("Ngày sinh sai định dạng!!!");
            jLabel_loingaysinh.setVisible(true);
            ktdate = false;
        } else {
            jLabel_loingaysinh.setVisible(false);
            ktdate = true;
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ngaysinhKeyReleased

    private void jTextField_hotenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_hotenKeyReleased

        if (jTextField_hoten.getText().equals("")) {
            jLabel_loiHoten.setText("Họ tên không được bỏ trống!!!");
            jLabel_loiHoten.setVisible(true);
            ktHoten = false;
        } else {
            jLabel_loiHoten.setVisible(false);
            ktHoten = true;
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_hotenKeyReleased

    private void jTextField_namnhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_namnhKeyReleased
        if (jTextField_namnh.getText().equals("")) {
            jLabel_loinamnh.setText("Năm nhập học không được bỏ trống!!!");
            jLabel_loinamnh.setVisible(true);
            ktNamNh = false;
        } else if (!jTextField_namnh.getText().matches("\\d{4}")) {
            jLabel_loinamnh.setText("Năm nhập học không hợp lệ!!!");
            jLabel_loinamnh.setVisible(true);
            ktNamNh = false;
        } else {
            jLabel_loinamnh.setVisible(false);
            ktNamNh = true;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_namnhKeyReleased

    private void jTextField_sdtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_sdtKeyReleased
        if (jTextField_sdt.getText().equals("")) {
            jLabel_loiSdt.setText("Số điện thoại không được bỏ trống!!!");
            jLabel_loiSdt.setVisible(true);
            ktSDT = false;
        } else if (!jTextField_sdt.getText().matches("0\\d{9,10}")) {
            jLabel_loiSdt.setText("Số điện thoại không đúng định dạng!!!");
            jLabel_loiSdt.setVisible(true);
            ktSDT = false;
        } else {
            jLabel_loiSdt.setVisible(false);
            ktSDT = true;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_sdtKeyReleased

    private void jTextField_diachiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_diachiKeyReleased
        if (jTextField_diachi.getText().equals("")) {
            jLabel_loiDiachi.setText("Địa chỉ không được bỏ trống!!!");
            jLabel_loiDiachi.setVisible(true);
            ktDiachi = false;
        } else {
            jLabel_loiDiachi.setVisible(false);
            ktDiachi = true;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_diachiKeyReleased

    private void jComboBox_malopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_malopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_malopActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_cancel;
    private javax.swing.JButton jButton_sua;
    private javax.swing.JComboBox<String> jComboBox_malop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_loiDiachi;
    private javax.swing.JLabel jLabel_loiHoten;
    private javax.swing.JLabel jLabel_loiSdt;
    private javax.swing.JLabel jLabel_loinamnh;
    private javax.swing.JLabel jLabel_loingaysinh;
    private javax.swing.JLabel jLabel_masv;
    private javax.swing.JRadioButton jRadioButton_nam;
    private javax.swing.JRadioButton jRadioButton_nu;
    private javax.swing.JTextField jTextField_diachi;
    private javax.swing.JTextField jTextField_hoten;
    private javax.swing.JTextField jTextField_namnh;
    private javax.swing.JTextField jTextField_ngaysinh;
    private javax.swing.JTextField jTextField_sdt;
    // End of variables declaration//GEN-END:variables
}
