/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.admin;

import Views.admin.QLLopTC;
import Controller.LopTCController;
import Controller.KetNoiSQL;
import Controller.MonHocController;
import classObj.LopTC;
import classObj.Monhoc;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author TuanVi
 */
public class SuaLopTC extends javax.swing.JFrame {

    private boolean ktHK = true, ktNhom = true, ktsvmax = true, ktsvmin = true;

    /**
     * Creates new form SuaLopTC
     *
     * @param maLop
     */
    public SuaLopTC(int maLop) {
        initComponents();
        loadComboBoxMaMH();
        layLopTC(maLop);
        jLabel_malop.setText(String.valueOf(maLop));
    }

    private void loadComboBoxMaMH() {

        for (Object object : MonHocController.getAllmaMonHoc()) {
            jComboBox_maMonHoc.addItem(String.valueOf(object));
        }

    }

    private void layLopTC(int maLop) {
        LopTC rs = LopTCController.ktMaLopTrung(maLop);
        jComboBox_maMonHoc.setSelectedItem(rs.getMaMH());
        jComboBox_nienkhoa.setSelectedItem(rs.getNienKhoa());
        jTextField_hocKy.setText(String.valueOf(rs.getHocKy()));
        jTextField_nhom.setText(String.valueOf(rs.getNhom()));
        jTextField_soSvMax.setText(String.valueOf(rs.getSvMax()));
        jTextField_soSvMin.setText(String.valueOf(rs.getSvMin()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_nhom = new javax.swing.JTextField();
        jTextField_soSvMax = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_soSvMin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel_hocKy = new javax.swing.JLabel();
        jComboBox_maMonHoc = new javax.swing.JComboBox<>();
        jLabel_nhom = new javax.swing.JLabel();
        jComboBox_nienkhoa = new javax.swing.JComboBox<>();
        jLabel_svMax = new javax.swing.JLabel();
        jTextField_hocKy = new javax.swing.JTextField();
        jButton_suaLop = new javax.swing.JButton();
        jButton_thoat = new javax.swing.JButton();
        jLabel_loiSvMin = new javax.swing.JLabel();
        jLabel_malop = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SỬA LỚP TÍN CHỈ");

        jTextField_nhom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nhomActionPerformed(evt);
            }
        });
        jTextField_nhom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_nhomKeyReleased(evt);
            }
        });

        jTextField_soSvMax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_soSvMaxKeyReleased(evt);
            }
        });

        jLabel4.setText("Mã môn học");

        jTextField_soSvMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_soSvMinActionPerformed(evt);
            }
        });
        jTextField_soSvMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_soSvMinKeyReleased(evt);
            }
        });

        jLabel5.setText("Niên khóa");

        jLabel6.setText("Học kỳ");

        jLabel7.setText("Nhóm");

        jLabel3.setText("Mã lớp");

        jLabel8.setText("Số SV max");

        jLabel9.setText("Số SV min");

        jLabel_hocKy.setForeground(new java.awt.Color(255, 0, 0));

        jComboBox_maMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_maMonHocActionPerformed(evt);
            }
        });

        jLabel_nhom.setForeground(new java.awt.Color(255, 0, 0));

        jComboBox_nienkhoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2005-2006", "2006-2007", "2007-2008", "2008-2009", "2009-2010", "2010-2011", "2011-2012", "2012-2013", "2013-2014", "2014-2015", "2015-2016", "2016-2017", "2017-2018", "2018-2019", "2019-2020", "2020-2021", "2021-2022", "2022-2023", "2023-2024" }));
        jComboBox_nienkhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_nienkhoaActionPerformed(evt);
            }
        });

        jLabel_svMax.setForeground(new java.awt.Color(255, 0, 0));

        jTextField_hocKy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_hocKyKeyReleased(evt);
            }
        });

        jButton_suaLop.setText("SỬA");
        jButton_suaLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_suaLopActionPerformed(evt);
            }
        });

        jButton_thoat.setText("Thoát");
        jButton_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_thoatActionPerformed(evt);
            }
        });

        jLabel_loiSvMin.setForeground(new java.awt.Color(255, 0, 0));

        jLabel_malop.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jButton_suaLop)
                        .addGap(171, 171, 171)
                        .addComponent(jButton_thoat))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel8))
                            .addComponent(jLabel3))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_malop, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_hocKy, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBox_maMonHoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox_nienkhoa, 0, 194, Short.MAX_VALUE))
                            .addComponent(jLabel_hocKy, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_nhom, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_soSvMax, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_soSvMin, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_nhom, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_svMax, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_loiSvMin, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_malop, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox_maMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jComboBox_nienkhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_hocKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(8, 8, 8)
                        .addComponent(jLabel_hocKy, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_nhom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_nhom, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_soSvMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_svMax, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_soSvMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(jLabel_loiSvMin, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_suaLop)
                    .addComponent(jButton_thoat))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_nhomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nhomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nhomActionPerformed

    private void jComboBox_nienkhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_nienkhoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_nienkhoaActionPerformed

    private void jButton_suaLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_suaLopActionPerformed
        if (ktHK == true && ktNhom == true && ktsvmax == true && ktsvmin == true) {
            LopTC loptc = new LopTC();
            loptc.setMaLop(Integer.valueOf(jLabel_malop.getText()));
            loptc.setMaMH((String) jComboBox_maMonHoc.getSelectedItem());
            loptc.setNienKhoa((String) jComboBox_nienkhoa.getSelectedItem());
            loptc.setHocKy(Integer.parseInt(jTextField_hocKy.getText()));
            loptc.setNhom(Integer.parseInt(jTextField_nhom.getText()));
            loptc.setSvMax(Integer.parseInt(jTextField_soSvMax.getText()));
            loptc.setSvMin(Integer.parseInt(jTextField_soSvMin.getText()));
            LopTC ktLoptc = LopTCController.getLopWhere(loptc.getMaMH(), loptc.getNienKhoa(), loptc.getNhom(), loptc.getHocKy());
            if (Integer.valueOf(jTextField_soSvMin.getText()) > Integer.valueOf(jTextField_soSvMax.getText())
                    || Integer.valueOf(jTextField_soSvMin.getText()) == Integer.valueOf(jTextField_soSvMax.getText())) {
                JOptionPane.showMessageDialog(rootPane, "Sinh viên min không được lớn hơn hoặc bằng Sinh viên max!!!");
            } else if (ktLoptc != null) {
                JOptionPane.showMessageDialog(rootPane, "Không được trùng Mã Môn Học, Niên Khoá, Nhóm, Học Kỳ!!!");
            } else {
                int confirm = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc muốn Sửa không?");
                if (confirm == JOptionPane.YES_OPTION) {
                    try {
                        LopTCController.suaLop(loptc);
                        JOptionPane.showMessageDialog(rootPane, "Sửa thành công!!!");
                        new QLLopTC().setVisible(true);
                        this.dispose();
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Không được để trống!!!");
        }
    }//GEN-LAST:event_jButton_suaLopActionPerformed

    private void jButton_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_thoatActionPerformed
        try {
            new QLLopTC().setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(SuaLopTC.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_jButton_thoatActionPerformed

    private void jTextField_hocKyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_hocKyKeyReleased
        String regexHK = "^[123]$";
        String megHK = "Học kì không được để trống!!!";
        String reHK = "Định dạng học kì không đúng!!!";
        if (jTextField_hocKy.getText().equals("")) {
            jLabel_hocKy.setText(megHK);
            jLabel_hocKy.setVisible(true);
            ktHK = false;
        } else if (!jTextField_hocKy.getText().matches(regexHK)) {
            jLabel_hocKy.setText(reHK);
            jLabel_hocKy.setVisible(true);
            ktHK = false;
        } else {
            jLabel_hocKy.setVisible(false);
            ktHK = true;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_hocKyKeyReleased

    private void jTextField_nhomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nhomKeyReleased
        String regexNhom = "^\\d$";
        String megNhom = "Nhóm không được để trống!!!";
        String reNhom = "Định dạng nhóm không đúng!!!";
        if (jTextField_nhom.getText().equals("")) {
            jLabel_nhom.setText(megNhom);
            jLabel_nhom.setVisible(true);
            ktNhom = false;
        } else if (!jTextField_nhom.getText().matches(regexNhom)) {
            jLabel_nhom.setText(reNhom);
            jLabel_nhom.setVisible(true);
            ktNhom = false;
        } else {
            ktNhom = true;
            jLabel_nhom.setVisible(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nhomKeyReleased

    private void jTextField_soSvMaxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_soSvMaxKeyReleased
        String regexSvMax = "^[12][0-9][0-9]?$|^[3-9][0-9]$";
        String megSVMax = "Điền vào số sinh viên max!!!";
        String regexmax = "max > 10 && max < 300";
        if (jTextField_soSvMax.getText().equals("")) {
            jLabel_svMax.setText(megSVMax);
            jLabel_svMax.setVisible(true);
            ktsvmax = false;
        } else if (!jTextField_soSvMax.getText().matches(regexSvMax)) {
            jLabel_svMax.setText(regexmax);
            jLabel_svMax.setVisible(true);
            ktsvmax = false;
        } else {
            ktsvmax = true;
            jLabel_svMax.setVisible(false);
        }
    }//GEN-LAST:event_jTextField_soSvMaxKeyReleased

    private void jTextField_soSvMinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_soSvMinKeyReleased
        String regexSvMin = "^[1-9][0-9]$";
        String regexMin = "min > 10 && min < 100";
        String megSVMin = "Điền vào số sinh viên min!!!";
        if (jTextField_soSvMin.getText().equals("")) {
            jLabel_loiSvMin.setText(megSVMin);
            jLabel_loiSvMin.setVisible(true);
            ktsvmin = false;
        } else if (!jTextField_soSvMin.getText().matches(regexSvMin)) {
            jLabel_loiSvMin.setText(regexMin);
            jLabel_loiSvMin.setVisible(true);
            ktsvmin = false;
        } else {
            ktsvmin = true;
            jLabel_loiSvMin.setVisible(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_soSvMinKeyReleased

    private void jTextField_soSvMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_soSvMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_soSvMinActionPerformed

    private void jComboBox_maMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_maMonHocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_maMonHocActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SuaLopTC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SuaLopTC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SuaLopTC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SuaLopTC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SuaLopTC().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_suaLop;
    private javax.swing.JButton jButton_thoat;
    private javax.swing.JComboBox<String> jComboBox_maMonHoc;
    private javax.swing.JComboBox<String> jComboBox_nienkhoa;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_hocKy;
    private javax.swing.JLabel jLabel_loiSvMin;
    private javax.swing.JLabel jLabel_malop;
    private javax.swing.JLabel jLabel_nhom;
    private javax.swing.JLabel jLabel_svMax;
    private javax.swing.JTextField jTextField_hocKy;
    private javax.swing.JTextField jTextField_nhom;
    private javax.swing.JTextField jTextField_soSvMax;
    private javax.swing.JTextField jTextField_soSvMin;
    // End of variables declaration//GEN-END:variables
}
