package Views.user;


import Controller.SinhVienController;
import Encryption.MD5;
import Views.Login;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author LE HIEU
 */
public class ChangePassword extends javax.swing.JFrame {

    private String userName;
    private boolean ktmkCu, ktnewpass, ktxacnhan;

    /**
     * Creates new form ChangePassword
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton_xacnhan = new javax.swing.JButton();
        jButton_thoat = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtextFiled_mkcu = new javax.swing.JPasswordField();
        jtextFiled_newPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jtextFiled_ConfirmPass = new javax.swing.JPasswordField();
        jLabel_mkcu = new javax.swing.JLabel();
        jLabel_newpassword = new javax.swing.JLabel();
        jLabel_xacnhanmk = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ĐỔI MẬT KHẨU");
        setBackground(new java.awt.Color(255, 255, 102));

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("MẬT KHẨU CŨ: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 49, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("MẬT KHẨU MỚI: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 49, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jButton_xacnhan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_xacnhan.setText("XÁC NHẬN");
        jButton_xacnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_xacnhanActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 49, 46, 0);
        jPanel1.add(jButton_xacnhan, gridBagConstraints);

        jButton_thoat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_thoat.setText("THOÁT");
        jButton_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_thoatActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 47, 0, 0);
        jPanel1.add(jButton_thoat, gridBagConstraints);

        jLabel3.setIcon(new javax.swing.ImageIcon("G:\\10\\QLSV\\src\\hinhanh\\136729120_236131321215679_1330693937606788859_n.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(46, 1, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        jtextFiled_mkcu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtextFiled_mkcuKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 129;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 22, 0, 33);
        jPanel1.add(jtextFiled_mkcu, gridBagConstraints);

        jtextFiled_newPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextFiled_newPasswordActionPerformed(evt);
            }
        });
        jtextFiled_newPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtextFiled_newPasswordKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 129;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 22, 0, 33);
        jPanel1.add(jtextFiled_newPassword, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("NHẬP LẠI MẬT KHẨU MỚI: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 49, 0, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        jtextFiled_ConfirmPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtextFiled_ConfirmPassKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 129;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 22, 0, 33);
        jPanel1.add(jtextFiled_ConfirmPass, gridBagConstraints);

        jLabel_mkcu.setForeground(new java.awt.Color(255, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 135;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 22, 0, 33);
        jPanel1.add(jLabel_mkcu, gridBagConstraints);

        jLabel_newpassword.setForeground(new java.awt.Color(204, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 135;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 22, 0, 33);
        jPanel1.add(jLabel_newpassword, gridBagConstraints);

        jLabel_xacnhanmk.setForeground(new java.awt.Color(255, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 135;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 22, 0, 33);
        jPanel1.add(jLabel_xacnhanmk, gridBagConstraints);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public ChangePassword(String username) {
        initComponents();
        this.userName = username;
    }


    private void jtextFiled_newPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextFiled_newPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextFiled_newPasswordActionPerformed

    private void jButton_xacnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_xacnhanActionPerformed
        if (ktmkCu == true && ktnewpass == true && ktxacnhan == true) {
            String MD5_pass = MD5.getMd5(jtextFiled_mkcu.getText().trim());
            String matKhauMoi = jtextFiled_newPassword.getText().trim();
            String xacNhanMK = jtextFiled_ConfirmPass.getText().trim();
            if (!matKhauMoi.equals(xacNhanMK)) {
                JOptionPane.showMessageDialog(rootPane, "Mật khẩu mới không trùng khớp!!!");
            } else if (!SinhVienController.ktPassWord(userName, MD5_pass)) {
                JOptionPane.showMessageDialog(rootPane, "Mật khẩu cũ không đúng!!!");
            } else {
                SinhVienController.doiMatKhau(userName, matKhauMoi);
                JOptionPane.showMessageDialog(rootPane, "Đổi mật khẩu thành công!!!");
                this.dispose();
                new Login().setVisible(true);
            }
        }
    }//GEN-LAST:event_jButton_xacnhanActionPerformed

    private void jtextFiled_mkcuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtextFiled_mkcuKeyReleased
        if (jtextFiled_mkcu.getText().trim().equals("")) {
            ktmkCu = false;
            jLabel_mkcu.setText("password is invalid");
            jLabel_mkcu.setVisible(true);
        } else {
            ktmkCu = true;
            jLabel_mkcu.setVisible(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextFiled_mkcuKeyReleased

    private void jtextFiled_newPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtextFiled_newPasswordKeyReleased
        if (jtextFiled_newPassword.getText().trim().equals("")) {
            ktnewpass = false;
            jLabel_newpassword.setText("newpassword is invalid");
            jLabel_newpassword.setVisible(true);
        } else {
            ktnewpass = true;
            jLabel_newpassword.setVisible(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextFiled_newPasswordKeyReleased

    private void jtextFiled_ConfirmPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtextFiled_ConfirmPassKeyReleased
        if (jtextFiled_ConfirmPass.getText().trim().equals("")) {
            ktxacnhan = false;
            jLabel_xacnhanmk.setText("ConfirmPass is invalid");
            jLabel_xacnhanmk.setVisible(true);
        } else {
            ktxacnhan = true;
            jLabel_xacnhanmk.setVisible(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextFiled_ConfirmPassKeyReleased

    private void jButton_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_thoatActionPerformed
       this.dispose();
       new SVLOGIN(userName).setVisible(true);
    }//GEN-LAST:event_jButton_thoatActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_thoat;
    private javax.swing.JButton jButton_xacnhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_mkcu;
    private javax.swing.JLabel jLabel_newpassword;
    private javax.swing.JLabel jLabel_xacnhanmk;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jtextFiled_ConfirmPass;
    private javax.swing.JPasswordField jtextFiled_mkcu;
    private javax.swing.JPasswordField jtextFiled_newPassword;
    // End of variables declaration//GEN-END:variables

}
