package Views.user;


import Controller.SinhVienController;
import Views.Login;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LE HIEU
 */
public class SVLOGIN extends javax.swing.JFrame {
      private  String masv;
    /** Creates new form SVLOGIN */
    public SVLOGIN(String masv) {
        initComponents();
        jLabel2_namesv.setText(SinhVienController.ktTrung_MASV(masv).getHoTen());
        this.masv=masv;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1_xemdiem = new javax.swing.JButton();
        jButton2_dkiloptc = new javax.swing.JButton();
        jButton3_doimk = new javax.swing.JButton();
        jButton4_thoat = new javax.swing.JButton();
        jLabel2_chao = new javax.swing.JLabel();
        jLabel2_namesv = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ ĐIỂM SINH VIÊN");

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SINH VIÊN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon("G:\\10\\QLSV\\src\\hinhanh\\136729120_236131321215679_1330693937606788859_n.png")); // NOI18N

        jButton1_xemdiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1_xemdiem.setText("XEM ĐIỂM");
        jButton1_xemdiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_xemdiemActionPerformed(evt);
            }
        });

        jButton2_dkiloptc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2_dkiloptc.setText("ĐĂNG KÝ LỚP TÍN CHỈ");

        jButton3_doimk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3_doimk.setText("ĐỔI MẬT KHẨU");
        jButton3_doimk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_doimkActionPerformed(evt);
            }
        });

        jButton4_thoat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4_thoat.setText("ĐĂNG XUẤT");
        jButton4_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_thoatActionPerformed(evt);
            }
        });

        jLabel2_chao.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2_chao.setText("CHÀO");

        jLabel2_namesv.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2_namesv.setForeground(new java.awt.Color(255, 102, 102));

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(134, 134, 134)
                        .add(jLabel2_chao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jLabel2_namesv, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 180, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(49, 49, 49)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 381, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabel1)
                                .add(86, 86, 86)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jButton1_xemdiem, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(jButton2_dkiloptc, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(jButton3_doimk, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(jButton4_thoat, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(29, 29, 29)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2_chao, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabel2_namesv, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(28, 28, 28)
                .add(jButton1_xemdiem)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(31, 31, 31)
                        .add(jButton2_dkiloptc)
                        .add(28, 28, 28)
                        .add(jButton3_doimk)
                        .add(27, 27, 27))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel1)
                        .add(18, 18, 18)))
                .add(jButton4_thoat)
                .add(26, 26, 26))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_thoatActionPerformed
       this.dispose();
       new Login().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4_thoatActionPerformed

    private void jButton3_doimkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_doimkActionPerformed
        this.dispose();
        new ChangePassword(masv).setVisible(true);
    }//GEN-LAST:event_jButton3_doimkActionPerformed

    private void jButton1_xemdiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_xemdiemActionPerformed
          new SVxemDiem(masv).setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1_xemdiemActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_xemdiem;
    private javax.swing.JButton jButton2_dkiloptc;
    private javax.swing.JButton jButton3_doimk;
    private javax.swing.JButton jButton4_thoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2_chao;
    private javax.swing.JLabel jLabel2_namesv;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
