package Views.user;

import Controller.DiemController;
import Controller.LopTCController;
import Controller.MonHocController;
import Controller.SinhVienController;
import classObj.DIEM;
import classObj.LopTC;
import classObj.Monhoc;
import classObj.Sinhvien;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author LE HIEU
 */
public class SVxemDiem extends javax.swing.JFrame {

    /**
     * Creates new form SVxemDiem
     */
    public SVxemDiem(String masv) {
        initComponents();
        loadThongTinSV(masv);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_tenSV = new javax.swing.JLabel();
        jLabel_lop = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_thongtinsv = new javax.swing.JTable();
        jButton_thoat = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ĐIỂM SINH VIÊN");

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "XEM ĐIỂM SINH VIÊN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("HỌC VIỆN CÔNG NGHỆ BƯU CHÍNH VIỄN THÔNG");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 28, 465, 25));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setText("CƠ SỞ THÀNH PHỐ HỒ CHÍ MINH");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 59, 325, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("G:\\10\\QLSV\\src\\hinhanh\\136729120_236131321215679_1330693937606788859_n.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 17, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 92, 457, 18));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("TÊN SINH VIÊN: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 128, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("LỚP: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 128, -1, -1));

        jLabel_tenSV.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jPanel1.add(jLabel_tenSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 128, 160, 15));

        jLabel_lop.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jPanel1.add(jLabel_lop, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 128, 93, 15));

        jTable_thongtinsv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã lớp tín chỉ", "Mã môn học", "Tên môn học", "Điểm", "Nhóm", "Học kỳ", "Niên khóa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_thongtinsv);
        if (jTable_thongtinsv.getColumnModel().getColumnCount() > 0) {
            jTable_thongtinsv.getColumnModel().getColumn(0).setMinWidth(40);
            jTable_thongtinsv.getColumnModel().getColumn(0).setMaxWidth(40);
            jTable_thongtinsv.getColumnModel().getColumn(4).setMinWidth(50);
            jTable_thongtinsv.getColumnModel().getColumn(4).setMaxWidth(50);
            jTable_thongtinsv.getColumnModel().getColumn(5).setMinWidth(50);
            jTable_thongtinsv.getColumnModel().getColumn(5).setMaxWidth(50);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 161, 620, 130));

        jButton_thoat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_thoat.setText("QUAY LẠI");
        jButton_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_thoatActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_thoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 114, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 299, 453, 10));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 902, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_thoatActionPerformed
         this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_thoatActionPerformed
    private void loadThongTinSV(String masv) {
        Sinhvien sv = SinhVienController.ktTrung_MASV(masv);
        jLabel_tenSV.setText(sv.getHoTen());
        jLabel_lop.setText(sv.getMalOP());
        DefaultTableModel dtm = (DefaultTableModel) jTable_thongtinsv.getModel();
        dtm.setNumRows(0);
        int i=1;
        for (DIEM diem : DiemController.getThongtinSV(masv)) {
             LopTC a=LopTCController.ktMaLopTrung(diem.getMaLopTC());
              Monhoc mh=MonHocController.ktMonhoc(a.getMaMH());
            dtm.addRow(new Object[]{
                i++,diem.getMaLopTC(),mh.getMAMH(),mh.getTenMH(),diem.getDiem(),a.getNhom(),a.getHocKy(),a.getNienKhoa()
            });
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_thoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_lop;
    private javax.swing.JLabel jLabel_tenSV;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable_thongtinsv;
    // End of variables declaration//GEN-END:variables

}
